# Generated by Django 6.0.6 on 2026-07-01 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255)),
                ('ice', models.CharField(blank=True, max_length=50)),
                ('if_number', models.CharField(blank=True, max_length=50)),
                ('rc', models.CharField(blank=True, max_length=50)),
                ('cnss', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('tva_regime', models.CharField(choices=[('monthly', 'Mensuelle'), ('quarterly', 'Trimestrielle'), ('exempt', 'Exonéré')], default='quarterly', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'company_name'], name='clients_cli_organiz_8fd6b1_idx'), models.Index(fields=['organization', 'ice'], name='clients_cli_organiz_435bf4_idx'), models.Index(fields=['organization', 'is_active'], name='clients_cli_organiz_c7479f_idx')],
            },
        ),
    ]
